trigger:
- none
stages:
- stage: Terrafrom_Apply_Task
  jobs:
  - job: Terrafrom_Apply_Task
    displayName: 'Terrafrom_Apply_Task'
    pool:
      vmImage: 'ubuntu-latest'

    steps:
    - checkout: self
    - task: AzureCLI@2
      name: set_variables
      displayName: Terrafrom_Apply_Task
      inputs:
        azureSubscription: 'random'
        addSpnToEnvironment: true
        scriptType: pscore
        scriptLocation: inlineScript
        inlineScript: |
          Write-Host "##vso[task.setvariable variable=ARM_USE_OIDC]true"
          Write-Host "##vso[task.setvariable variable=ARM_OIDC_TOKEN]$env:idToken"
          Write-Host "##vso[task.setvariable variable=ARM_CLIENT_ID]$env:servicePrincipalId"
          Write-Host "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show --query id -o tsv)"
          Write-Host "##vso[task.setvariable variable=ARM_TENANT_ID]$env:tenantId"
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          terraform init
        workingDirectory: '$(System.DefaultWorkingDirectory)/usage-example'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          terraform plan
        workingDirectory: '$(System.DefaultWorkingDirectory)/usage-example'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
    - task: Bash@3
      inputs:
        targetType: 'inline'
        script: |
          terraform apply --auto-approve
        workingDirectory: '$(System.DefaultWorkingDirectory)/usage-example'
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
     
     
    